name: combined_barcode_scanner_honeywell
description: Combined Barcode scanner package that interfaces with honeywell scanners
version: 1.3.0
homepage: https://github.com/icapps/combined_barcode_scanner
repository: https://github.com/icapps/combined_barcode_scanner
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  combined_barcode_scanner: 
    git:
      url: https://github.com/airsphere-gmbh/combined_barcode_scanner.git
      ref: work/updateHoneywell
  flutter:
    sdk: flutter
  honeywell_scanner: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

## snippet used for testing changes in combined_barcode_scanner during development:
# dependency_overrides:
#   combined_barcode_scanner:
#     path: ../..

flutter:
