name: combined_barcode_scanner_fast
description: Combined Barcode scanner package that interfaces the fast_barcode_scanner package
version: 1.1.0
homepage: https://github.com/icapps/combined_barcode_scanner
repository: https://github.com/icapps/combined_barcode_scanner

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=2.0.0"

dependencies:
  combined_barcode_scanner: ^1.1.0
  icapps_fast_barcode_scanner: ^1.4.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

#dependency_overrides:
# combined_barcode_scanner:
#   path: ../..

flutter:
